#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

spring:
  application:
    name: bank_rest-main

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml
    parameters:
      ADMIN_BCRYPT: "$2a$10$6Q3gia/juxx9lH4EEmgPWOYY9jBbxZcxQ7iHVxANSMpPCvYIFFmBq"

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc.core: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
      endpoint:
        health:
          show-details: always

jwt_secret: 8f2e4b0093a94c35b6d17fcf0a51980485ae71b4f6f064f3869e7092e7b40acd

app:
  security:
    admin-activation-code: work2025admin
    jwt:
      expiration: PT1H   # ISO-8601 Duration: 1 час. Примеры: PT30M, PT24H, P7D
  cors:
    allowed-origins: "*"

card:
  bin: "400000"
  currency: "USD"